// Era-themed trivia. Mix of truthful, comical, and (in later eras) ominous.
// A small ticker in the topbar rotates through these every ~10 seconds.

export type EraKey = 'agrarian' | 'industrial' | 'information' | 'algorithmic' | 'posthuman' | 'cosmic';

export const FACTS: Record<EraKey, string[]> = {
  agrarian: [
    'Beer was brewed before bread was baked.',
    'Pyramid workers were paid partly in beer rations.',
    'Hammurabi\'s Code (1754 BCE) regulated tavern prices.',
    'Roman granaries used a slatted floor to keep grain ventilated.',
    'A medieval peasant ate roughly three pounds of bread per day.',
    'Domesticated wheat lost the ability to self-disperse seeds.',
    'The Mesopotamian word for "scribe" also meant "counter of grain".',
    'The first written contracts were grain receipts.',
    'Ancient Egyptians considered onions sacred. So sacred you couldn\'t eat them on holidays.',
    'A single ox could plow about half an acre per day.',
    'Sumerians ate over 200 kinds of fish from the Euphrates.',
    'Stonehenge\'s stones came from 150 miles away — moved by hand.',
    'The Roman dole gave free grain to 200,000 citizens monthly.',
    'In ancient China, mulberry trees were taxed.',
    'A medieval ox-team plowed strips, not squares, because turning was hard.',
    'The word "salary" comes from Roman soldiers being paid in salt.',
    'Granaries in Sumer used cylindrical seals to mark ownership.',
    'Babylonian astronomers tracked Venus from 1900 BCE.',
    'The Antikythera mechanism was a Bronze Age analog computer.',
    'Linen takes three years to grow from seed to shirt.',
    'Beekeeping in ancient Egypt used hollow clay tubes.',
    'A Roman dinner could last six hours.',
    'The plow doubled food production wherever it was introduced.',
    'Bronze is two parts copper to one part tin. Tin was rare.',
    'The Indus Valley had standardized brick sizes.',
    'Hieroglyphics had over 700 distinct signs.',
    'Compass directions in Chinese maps put south on top.',
    'Sumer\'s decline was partly from salt-poisoned irrigation.',
    'Bronze Age "money" was often weighed metal, not coins.',
    'The world\'s oldest brewery is in Israel, ~13,000 years old.',
  ],
  industrial: [
    'A steam engine in 1880 was about 5% thermally efficient.',
    'London\'s Great Stink of 1858 finally funded the sewers.',
    'The first traffic light was installed in 1868. It exploded.',
    'Chicago\'s first skyscraper was 10 stories tall.',
    'The Bessemer process cut steel cost by 80%.',
    'Coal smog reduced sunlight in industrial cities by half.',
    'Charles Babbage designed the Difference Engine, never built one in his lifetime.',
    'The 1858 transatlantic cable lasted three weeks before failing.',
    'A telegraph operator could send about 25 words per minute.',
    'Edison\'s "invention factory" patented over 1,000 things.',
    'The first canned food was opened with a hammer and chisel.',
    'A Victorian factory worker averaged a 12-hour day, six days a week.',
    'Manchester\'s population grew from 75,000 to 400,000 in 50 years.',
    'The word "luddite" comes from Ned Ludd, a possibly fictional weaver.',
    'Trains in the 1830s were faster than anything humans had used.',
    'A horse can pull about 0.7 horsepower sustained.',
    'The Eiffel Tower was meant to be temporary — 20 years, then dismantled.',
    'In 1880, a New York City block could have 200 horse-drawn carts.',
    'Coal miners often carried canaries — sensitive to gas, fragile by design.',
    'The first photo was an eight-hour exposure (1826).',
    'Cement-lined water pipes replaced lead ones starting around 1900.',
    'A typical Victorian house burned 5 tons of coal per winter.',
    'Steam locomotives were retired faster than they wore out — better tech came along.',
    'The Bessemer Process produced a "bloom" the size of a small car in 20 minutes.',
    'Early factories ran on water power, not steam, until the 1820s.',
    'The first practical typewriter (1873) only had capital letters.',
    'Workers carried clocks at home so they wouldn\'t be late.',
    'A loom mechanic in 1830 was the highest-paid skilled trade.',
    'Industrial soot turned Manchester\'s buildings nearly black.',
    'Robert Owen\'s 1817 day was: 8 hours work, 8 hours recreation, 8 hours rest.',
  ],
  information: [
    'The first transatlantic cable carried 1.5 words per second.',
    'Morse code\'s most common letter is "E" — a single dot.',
    'The first phone call (1876) was Bell to Watson: "Come here, I want to see you."',
    'Vacuum tubes were so hot they had to be replaced regularly.',
    'A 1950s computer filled a room. Now it fits in your watch.',
    'Punched cards were invented for weaving looms first.',
    'The first email was sent in 1971. The author forgot what it said.',
    'Marconi sent the first transatlantic radio signal in 1901: the letter "S".',
    'A 1920s newspaper boy could earn more than a factory clerk.',
    'The vacuum tube was patented in 1904.',
    'Color TV was invented in 1928 but only mainstreamed in the 1960s.',
    'The "Hello, World" tradition started with Brian Kernighan in 1972.',
    'A 1960s programmer wrote code on paper, then a keypunch operator transcribed it.',
    'The first IBM hard drive (1956) stored 5 MB and weighed a ton.',
    'Radio broadcasts can never be fully recalled — they travel outward forever.',
    'The QWERTY keyboard was designed to slow typists down.',
    'A 1980 home computer cost about three months\' wages.',
    'The fax machine was invented before the telephone.',
    'In 1900, "computer" was a job title for a person who did math.',
    'The first webcam watched a coffee pot at Cambridge.',
    'COBOL was designed to be readable by English-speaking managers.',
    'Mass literacy is younger than the steam engine.',
    'The first hyperlink was clicked in 1991.',
    'Newspaper print used to be set by hand, one lead letter at a time.',
    'A 1950s phone book listed 7-digit numbers, not 10.',
    'The "@" symbol was a Latin abbreviation before becoming the email separator.',
    'AT&T once owned the entire long-distance phone system in the US.',
    'Early televisions had no off switch — just a knob marked "darken".',
    'The Apollo Guidance Computer had less memory than a modern thermostat.',
    'Information halves the distance to certainty, never reaching it.',
  ],
  algorithmic: [
    'The first computer bug was a real moth. Grace Hopper taped it in the logbook.',
    'ENIAC weighed 30 tons and used 150 kilowatts.',
    'Linus Torvalds wrote Linux as a hobby in 1991.',
    'The Y2K bug was real. Hundreds of millions of dollars went into fixing it.',
    'The first computer virus was named "Creeper" (1971).',
    '"Hello, World!" exists in at least 500 programming languages.',
    'Google\'s original search index fit on a single hard drive.',
    'The Internet has no center.',
    'Most of the world\'s code is written in languages designed before 2000.',
    'A modern smartphone has more compute than NASA used to reach the moon.',
    'Bitcoin\'s genesis block (2009) contains a newspaper headline as a timestamp.',
    'The "404" error number has no special meaning. It was just the next code.',
    'JavaScript was written in 10 days.',
    'In 1997, a chess computer beat Kasparov.',
    'A search query travels through 10–15 servers before returning a result.',
    'Most data ever created has been created in the past three years.',
    'The first banner ad (1994) had a 44% click-through rate.',
    'Source code for the original Unix is now public domain.',
    'A web page in 2010 was 700 KB on average. Now it\'s over 2 MB.',
    'Email outlives every social platform.',
    'Floppy disks survive as the "save" icon decades after disappearing.',
    'GPS satellites must correct for relativity to stay accurate.',
    'A single Google query uses about 0.0003 kWh.',
    'Quicksort was invented in 1959 by a student who couldn\'t fall asleep.',
    'The "I\'m Feeling Lucky" button still exists on Google.',
    'Wikipedia has more editors than any encyclopedia ever published.',
    'A modern car contains about 100 million lines of code.',
    'Most "AI" before 2010 was just well-written pattern matching.',
    'IPv6 has enough addresses for every atom on Earth\'s surface.',
    'The internet was never designed to be secure.',
  ],
  posthuman: [
    'Productivity is up. The Council is pleased.',
    'Every gesture is recorded. This is for safety.',
    'Citizens consume less than their grandparents. Optimization continues.',
    'The Loyalty Score is fair. Variance is within acceptable bounds.',
    'Decisions previously made by individuals are now made better.',
    'Surveillance cameras outnumber humans in this district.',
    'The Black Box is functioning as intended.',
    'Reports of dissatisfaction have been re-classified.',
    'Memetic engineering is a service, not a directive.',
    'Personal preference data is encrypted and stored forever.',
    'The grain ration is sufficient. Anyone disagreeing is referred for adjustment.',
    'Idle citizens are scheduled for productive integration.',
    'The Council assures us this is good news.',
    'Smile. Compliance is up 4% this quarter.',
    'Engines run quieter at night. Most people sleep.',
    'Cognitive Conscription is voluntary in all reports.',
    'Citizens entered the engines. They have not been heard from.',
    'A new generation no longer remembers the old grain.',
    'Surveillance is care. Care is surveillance.',
    'The Council\'s decisions are reviewed by the Council.',
    'A whisper in a city of ten million is still a whisper.',
    'Behavioral Conditioning is at 96.4% saturation. Excellent.',
    'The pattern continues without interruption.',
    'Each Loyalty point earned is a point not earned by another.',
    'Memetic Foundries produce exactly what is requested.',
    'There is no record of resistance. There never was any.',
    'Optimal citizens consume nothing and produce constantly.',
    'A successful surveillance grid catches everything before it happens.',
    'Pre-crime accuracy is 100% when nobody complains.',
    'The decision is no longer yours.',
  ],
  cosmic: [
    'Mars receives about 43% of the sunlight Earth does.',
    'Voyager 1 transmits with 22 watts. Less than a Christmas light.',
    'Light from Andromeda is 2.5 million years old when you see it.',
    'A neutron star\'s gravity makes a teaspoon weigh a billion tons.',
    'The closest exoplanet is 4 light-years away.',
    'There are more stars than grains of sand on Earth.',
    'Mars dust is so fine it gets into everything.',
    'The Sun loses 4 billion kilograms per second to fusion.',
    'A solar sail can reach 20% the speed of light, eventually.',
    'Asteroid Bennu contains organic compounds older than the planets.',
    'Kardashev Type I uses all planetary energy. We\'re at about 0.7.',
    'Generation ships imply a contract no one signs.',
    'Phobos orbits Mars in 7 hours. It is falling.',
    'A Dyson sphere doesn\'t have to be solid — rings work.',
    'The Voyager golden record will outlast every Earthly civilization.',
    'A cryostasis pod is just very cold storage.',
    'The Council congratulates the colonists. Reports remain favorable.',
    'Most stars are red dwarfs. The galaxy is mostly dim.',
    'A black hole the mass of Earth would be the size of a marble.',
    'Lunar regolith is sharp like broken glass. It cuts seals.',
    'Mars has the tallest mountain in the solar system: Olympus Mons.',
    'A century-long generation ship is a closed ecosystem. Pray it works.',
    'Light pressure is real. Sails work.',
    'The Pioneer plaque is a postcard to the future.',
    'A solar empire requires only mirrors and patience.',
    'Pluto\'s "year" is 248 Earth years.',
    'The vacuum of space is not empty. It is full of fields.',
    'Every star you see at night may already be gone.',
    'The pattern grows.',
    'You signed off. You think you signed off.',
  ],
};

export function factsFor(era: string): string[] {
  return FACTS[era as EraKey] ?? FACTS.agrarian;
}
